namespace WinAcmeGui.App.Localization;

public static partial class LocalizationTable
{
    private static LocalizedEntry[] Dashboard() =>
    [
        new("ActiveInstallation", "INSTALAÇÃO ATIVA", "ACTIVE INSTALLATION"),
        new("ConfigurationPath", "Caminho da configuração", "Configuration path"),
        new("ConfigurationPathUpper", "CAMINHO DA CONFIGURAÇÃO", "CONFIGURATION PATH"),
        new("Endpoint", "Endpoint ACME", "ACME endpoint"),
        new("EndpointUpper", "ENDPOINT ACME", "ACME ENDPOINT"),
        new("DetectedInstallation", "Instalação ativa", "Active installation"),
        new("RenewalCount", "renovações carregadas", "renewals loaded"),
        new("RenewalsLoaded", "Renovações carregadas", "Loaded renewals"),
        new("Health", "SAÚDE", "HEALTH"),
        new("ReadyToOperate", "Pronto para operar", "Ready to operate"),
        new("NotOperational", "Sem instalação operacional", "No operational installation"),
        new("ScheduledTask", "TAREFA AGENDADA", "SCHEDULED TASK"),
        new("VerifyInSystem", "Verificar no Sistema", "Check in System"),
        new("Scanning", "Procurando instalações do win-acme…", "Looking for win-acme installations…"),
        new("NoInstallation", "Nenhuma instalação encontrada", "No installation found"),
        new("NoInstallationHint",
            "Baixe o win-acme oficial ou selecione um wacs.exe existente para começar.",
            "Download official win-acme or select an existing wacs.exe to get started."),
        new("TotalRenewals", "TOTAL", "TOTAL"),
        new("HealthyRenewals", "SAUDÁVEIS", "HEALTHY"),
        new("DueSoonRenewals", "RENOVAR EM BREVE", "DUE SOON"),
        new("AttentionRenewals", "ATENÇÃO", "ATTENTION"),
        new("AttentionHint", "Falhas, expirados e documentos ilegíveis.", "Failures, expired and unreadable documents."),
        new("DueSoonHint", "Vencem nos próximos 30 dias.", "Expire within the next 30 days."),
        new("HealthyHint", "Sem pendências conhecidas.", "No known pending issues."),
        new("TotalHint", "Documentos *.renewal.json lidos.", "*.renewal.json documents read."),
        new("DiscoveryDiagnostics", "Diagnósticos da descoberta", "Discovery diagnostics"),
        new("DiagnosticsNone", "Nenhum diagnóstico registrado.", "No diagnostics recorded."),
        new("StatusHealthy", "Saudável", "Healthy"),
        new("StatusDueSoon", "Renovar em breve", "Due soon"),
        new("StatusFailed", "Falhou", "Failed"),
        new("StatusExpired", "Expirado", "Expired"),
        new("StatusUnreadable", "Não legível", "Unreadable"),
        new("Healthy", "Saudável", "Healthy"),
        new("DueSoon", "Renovar em breve", "Due soon"),
        new("Unreadable", "Não legível", "Unreadable")
    ];

    private static LocalizedEntry[] RenewalOperations() =>
    [
        new("FilterRenewals", "Filtrar por nome, domínio ou status", "Filter by name, domain or status"),
        new("SearchPlaceholder", "Buscar renovações…", "Search renewals…"),
        new("FilterAll", "Todas", "All"),
        new("FriendlyName", "Nome amigável", "Friendly name"),
        new("Domains", "Domínios", "Domains"),
        new("StatusColumn", "Status", "Status"),
        new("Diagnostics", "Diagnóstico", "Diagnostics"),
        new("Editable", "Editável", "Editable"),
        new("Renew", "Renovar", "Renew"),
        new("RenewTooltip", "Executa a renovação normal da linha selecionada.", "Runs the normal renewal for the selected row."),
        new("Force", "Forçar", "Force"),
        new("ForceTooltip", "Renova ignorando a janela de validade; pode emitir uma nova ordem ACME.",
            "Renews ignoring the validity window; may issue a new ACME order."),
        new("Cancel", "Cancelar", "Cancel"),
        new("CancelTooltip", "Remove a renovação do win-acme. Exige digitar o nome amigável.",
            "Removes the renewal from win-acme. Requires typing the friendly name."),
        new("Revoke", "Revogar", "Revoke"),
        new("RevokeTooltip", "Revoga o certificado emitido. Use apenas para chaves comprometidas.",
            "Revokes the issued certificate. Use only for compromised keys."),
        new("NewCertificateAction", "Novo certificado", "New certificate"),
        new("NoRenewalsTitle", "Nenhuma renovação carregada", "No renewals loaded"),
        new("NoRenewalsHint", "Renovações de uma instalação ativa aparecem aqui.",
            "Renewals from an active installation appear here."),
        new("NoMatchesTitle", "Nenhuma renovação corresponde ao filtro", "No renewal matches the filter"),
        new("NoMatchesHint", "Limpe a busca ou escolha outro status.", "Clear the search or pick another status."),
        new("ClearFilters", "Limpar filtros", "Clear filters"),
        new("SelectRenewalFirst", "Selecione uma renovação primeiro.", "Select a renewal first."),
        new("SelectInstallationFirst", "Selecione ou descubra uma instalação do win-acme primeiro.",
            "Select or discover a win-acme installation first."),
        new("ConfirmForceTitle", "Confirmar renovação forçada", "Confirm forced renewal"),
        new("ConfirmForceMessage", "Forçar a renovação pode emitir uma nova ordem ACME. Continuar?",
            "Forcing a renewal may issue a new ACME order. Continue?"),
        new("ConfirmCancelTitle", "Confirmar cancelamento", "Confirm cancellation"),
        new("ConfirmCancelMessage", "Digite o nome amigável para remover esta renovação do win-acme:",
            "Type the friendly name to remove this renewal from win-acme:"),
        new("ConfirmRevokeTitle", "Confirmar revogação", "Confirm revocation"),
        new("ConfirmRevokeMessage", "A revogação é destinada a chaves comprometidas. Digite o nome amigável:",
            "Revocation is intended for compromised keys. Type the friendly name:"),
        new("ConfirmationPrompt", "Digite exatamente o nome amigável para confirmar:", "Type the exact friendly name to confirm:"),
        new("ConfirmationMismatch", "O nome digitado não confere.", "The typed name does not match."),
        new("OperationRenew", "Renovação", "Renewal"),
        new("OperationForceRenew", "Renovação forçada", "Forced renewal"),
        new("OperationCancel", "Cancelamento", "Cancellation"),
        new("OperationRevoke", "Revogação", "Revocation"),
        new("OperationDiscovery", "Descoberta", "Discovery"),
        new("OperationDownload", "Download", "Download"),
        new("OperationCertificate", "Emissão de certificado", "Certificate issuance"),
        new("OperationSucceeded", "concluída com sucesso.", "completed successfully."),
        new("OperationFailed", "falhou.", "failed."),
        new("OperationCancelled", "cancelada.", "cancelled."),
        new("RefreshFailed", "A atualização do inventário falhou:", "Refreshing the inventory failed:")
    ];
}
